name: ğŸ§‹ BOBAX Core Build and Test
on: [push]
jobs:
  test:
    name: ğŸ›ï¸ Check the source code
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ğŸ§¶ Install dependency packages
        run: yarn install
      - name: ğŸ§ª Run tests
        run: yarn run test:nowatch
      - name: ğŸ” Lint
        run: yarn run lint
      - name: ğŸ’… Prettier
        run: yarn run format
