name: ğŸ§‹ BOBAX Core Build and Test
on:
  pull_request:
    branches:
      - '*'
jobs:
  test:
    name: ğŸ›ï¸ Check the source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ğŸ§¶ Install dependency packages
        run: yarn install
      - name: ğŸ” Lint
        run: yarn run lint
      - name: ğŸ’… Prettier
        run: yarn run format
